#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms

yum_install java-1.8.0-openjdk-devel unzip

http_proxy=$PROXY curl -sO http://www.mirrorservice.org/sites/ftp.apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -xzf apache-maven-3.3.9-bin.tar.gz
mv apache-maven-3.3.9 /usr/local
ln -sf /usr/local/apache-maven-3.3.9/bin/mvn /usr/local/bin

mkdir -p /home/demo/.m2
cp settings.xml /home/demo/.m2
chown -R demo:demo /home/demo/.m2

### Download and install JBDS
# http://download.eng.brq.redhat.com/released/jbdevstudio/8.1.0/jboss-devstudio-8.1.0.GA-installer-standalone.jar
curl -sO http://$APILISTENER/static/isos/jboss-devstudio-8.1.0.GA-installer-standalone.jar
java -jar jboss-devstudio-8.1.0.GA-installer-standalone.jar InstallConfigRecord.xml
cp 'Red Hat JBoss Developer Studio 8.1.0.GA.desktop' /usr/share/applications
install -m 0755 -o demo 'Red Hat JBoss Developer Studio 8.1.0.GA.desktop' /home/demo/Desktop

### Install Integration Stack
/usr/local/jbdevstudio/jbdevstudio -p2.os linux -application org.eclipse.equinox.p2.director -repository https://devstudio.redhat.com/earlyaccess/8.0/ -installIU org.fusesource.ide.camel.editor.feature.feature.group,org.fusesource.ide.core.feature.feature.group,org.fusesource.ide.fabric8.feature.feature.group,org.fusesource.ide.jmx.feature.feature.group,org.fusesource.ide.server.extensions.feature.feature.group,org.jboss.tools.fuse.transformation.feature.feature.group

### Download and install DV
DV_PATH="/home/demo/dv"

# http://download.eng.brq.redhat.com/released/JBossDV/6.2.0/jboss-dv-installer-6.2.0.redhat-3.jar
curl -sO http://download.eng.brq.redhat.com/released/JBossDV/6.2.0/jboss-dv-installer-6.2.0.redhat-3.jar
curl -sO https://raw.githubusercontent.com/DataVirtualizationByExample/DVWorkshop/master/dv-docker/software/dv-6.2.0.redhat-3-install.xml
java -jar jboss-dv-installer-6.2.0.redhat-3.jar dv-6.2.0.redhat-3-install.xml
sed -i -e 's/^#admin=/admin=/' $DV_PATH/standalone/configuration/application-users.properties

JAVA_HOME=/usr/lib/jvm/java-1.8.0 $DV_PATH/bin/standalone.sh &

sed -i -e 's/^#RUN_AS_USER=/RUN_AS_USER=demo/' $FUSE_PATH/bin/dv-service
chown -R demo:demo $DV_PATH

ln -s $DV_PATH/bin/dv-service /etc/init.d
chkconfig --add dv-service
chkconfig dv-service on
service dv-service start

firefox_set_homepage http://localhost:8080/
